name: ci
on:
  push:
    branches: deploy
jobs:
  build-and-upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t tables .
      - name: Copy tables from image
        run: 'docker cp $(docker create tables):/build/tables ./tables'
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: tables  
          path: ./tables
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: tables  
          path: ./tables