name: ci
runs-on: ubuntu-latest
on:
  push:
    branches: actions
jobs:
  upload-artifact:
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t tables < Dockerfile
      - name: Create container
        run: 'docker cp $(docker create tables):/build/tables /tables'
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: tables  
          path: /tables