name: Build and deploy to prod
on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t tables .
      - name: Copy tables from image
        run: 'docker cp $(docker create tables):/build/tables ./tables'
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: tables  
          path: ./tables
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: tables
          path: ./tables
      - name: Prepare staging directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          script: |
            rm -rf /tmp/staging/tables
            mkdir -p /tmp/staging/tables
      - name: Copy artifacts to prod staging directory
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          source: "tables/*"
          target: "/tmp/staging"
      - name: Seed prod database with staging tables
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          script: |
            export RAILS_ENV=production
            cd /root/madgrades/api.madgrades.com
            /root/.rbenv/shims/rake seed -- --path=/tmp/staging/tables
          command_timeout: 60m
