name: ci
on:
  push:
    branches: actions
jobs:
  upload-artifact:
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t tables < Dockerfile
      - name: Create container
        run: 'docker cp $(docker create tables):/build/tables /tables'
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: tables
          path: /tables
jobs:
  build:
    steps:
    - uses: actions/checkout@v3
    - name: Build docker images
      run: docker build -t local < .devcontainer/Dockerfile
    - name: Run tests
      run: docker run -it -v $PWD:/srv -w/srv local make test